Add more docs
sp-uulm/MiniLua pull request #103
Opened 2021-02-10 18:22 UTC by Lythenas

- [ ] guide for writing native functions
- [ ] working with values
- [ ] working with sourcechanges

2021-02-25 17:57 UTC, tn4799 requested changes

2021-02-25 17:57 UTC, tn4799 commented on src/stdlib.cpp
> +auto force(const CallContext& ctx) -> CallResult {
Please add tests for this method

2021-02-28 20:20 UTC, tn4799 requested changes

2021-02-28 20:20 UTC, tn4799 commented on include/tree_sitter/tree_sitter.hpp
> +     * @brief The numeric TypeId if the node.
```suggestion
     * @brief The numeric TypeId of the node.
```

2021-02-28 20:20 UTC, tn4799 commented on include/tree_sitter/tree_sitter.hpp
> +     * Returns `std::nullopt` this node is already the first sibling.
```suggestion
     * Returns `std::nullopt` if this node is already the first sibling.
```

2021-02-28 20:20 UTC, tn4799 commented on include/tree_sitter/tree_sitter.hpp
> +     * Returns `std::nullopt` this node is already the first named sibling.
```suggestion
     * Returns `std::nullopt` if this node is already the first named sibling.
```

2021-02-28 20:20 UTC, tn4799 commented on include/tree_sitter/tree_sitter.hpp
> +     * @brief Start position as byte offset.
```suggestion
     * @brief End position as byte offset.
```

2021-03-01 07:46 UTC, Lythenas commented on README.md
> +pip3 install jinja2 Pygments
Not sure what you mean by `-operator. They are in a code block.

Also this should work the same on Windows too.

2021-03-01 07:48 UTC, Lythenas commented on include/MiniLua/interpreter.hpp
>      [[nodiscard]] auto config() const -> const InterpreterConfig&;
Needed? Probably not. Best practice? Definitely yes. Without both a const method you can't use this method in a const function. And without the non-const method you can't do easy modifications like `x.config().all(true)`.

2021-03-01 07:50 UTC, Lythenas commented on include/MiniLua/values.hpp
>      auto operator[](const Value&) const -> const Value&;
Same as above.

2021-03-01 07:51 UTC, Lythenas commented on include/tree_sitter/tree_sitter.hpp
> +     * @brief The Tree-Sitter ABI version for this langauge.
Tree-Sitter calls it ABI in their code. Technically both are correct I think.

2021-03-01 12:17 UTC, CFU9 approved these changes

2021-03-01 12:25 UTC, tn4799 commented on include/tree_sitter/tree_sitter.hpp
> +     * @brief The Tree-Sitter ABI version for this langauge.
ok. but language is still written wrong.

2021-03-01 12:55 UTC, tn4799 commented on include/tree_sitter/tree_sitter.hpp
> +     * @brief The Tree-Sitter ABI version for this langauge.
I've updated the suggestion.

2021-03-01 12:56 UTC, Lythenas commented on include/tree_sitter/tree_sitter.hpp
> +     * @brief The Tree-Sitter ABI version for this langauge.
Oh I missed the language typo

2021-03-01 13:00 UTC, tn4799 approved these changes

2021-03-01 13:02 UTC, merged