Lua-Programms for testing
sp-uulm/MiniLua pull request #15
Opened 2020-09-07 14:21 UTC by tn4799

Lua-programs for testing the interpreter. 
more will be added in the future.
also formated the code

2020-09-07 14:41 UTC, Lythenas requested changes

2020-09-07 14:53 UTC, Lythenas commented
We should also stick with a naming convention for directories. I think `luaprograms` or `lua_programs` would be better.

2020-09-08 19:44 UTC, Lythenas approved these changes

2020-09-09 14:09 UTC, ThomasWitte commented
I like the example programs, they show that quite a lot is still missing from the interpreter.
From a quick glance (probably incomplete):

language features:
* comments
* multiline literals [[]]
* : operator
* implicit self
* for ... in

standard library:
* io.read
* io.write
* pairs
* string.len
* string.format
* table.insert
* tonumber
* tostring

2020-09-09 14:29 UTC, Lythenas commented
Some things will be fixed when we switch parsing to Tree-Sitter (e.g. comments, multiline literals) but a lot will need interpreter support and we need to implement the standard library.

Having a complete list of missing features would be nice but probably not possible.

We could also add the tests from the official lua interpreter: https://github.com/lua/lua/tree/master/testes

2020-11-10 15:09 UTC, Lythenas approved these changes

2020-11-10 15:09 UTC, merged