Ast-classes
sp-uulm/MiniLua pull request #79
Opened 2021-01-17 23:46 UTC by CFU9

2021-01-18 15:03 UTC, tn4799 commented
Do you know that you don't have to close and reopen an PR? Just commit to your branch and it will be automatically added to the PR if it is not closed. 
And the title and the description could be edited as well here at github

2021-01-21 13:46 UTC, Lythenas requested changes
I think generally it looks pretty good.

Can you please run the format script (and you should probably install the commit hook to do that automatically).

It may be worth merging some of the nodes. E.g.

- `VariableDeclaration` and `LocalVariableDeclaration` can be merged with a bool saying if it is local or not.
- `VariableDeclaration` and `VariableDeclarator` can be merged which might make it easier to use.

2021-01-21 15:59 UTC, Lythenas commented
`include/MiniLua/tree_sitter_ast.hpp` should be moved to `std/details/` because it does not need to be part of our public api. `src/core/tree_sitter_ast.cpp` should also be moved to `src/details/` and should probably be just named `ast.cpp`.

2021-01-22 13:21 UTC, Lythenas requested changes

2021-01-22 13:21 UTC, Lythenas commented on src/details/ast.cpp
> +    assert(node.child_count() == 3);
the asserts should be after the if because if we pass in the wrong type of node the exception is more appropriate.

2021-01-22 13:31 UTC, Lythenas approved these changes

2021-01-22 13:36 UTC, merged